// <auto-generated />
using System;
using AutoPartsErp.Modules.Finance.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoPartsErp.Modules.Finance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260915163403_AddFactPostings")]
    partial class AddFactPostings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Customers.CustomerTerms", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<int>("PaymentDueInDays")
                        .HasColumnType("integer")
                        .HasColumnName("payment_due_in_days");

                    b.Property<bool>("PaymentEndOfMonth")
                        .HasColumnType("boolean")
                        .HasColumnName("payment_end_of_month");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_customer_terms");

                    b.HasIndex("TenantId", "Code")
                        .HasDatabaseName("ix_customer_terms_tenant_code");

                    b.ToTable("customer_terms", "finance");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Ledger.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsPosting")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_posting");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_tenant_code");

                    b.ToTable("accounts", "finance");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Ledger.AccountingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("ReopenedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reopened_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_accounting_periods");

                    b.HasIndex("TenantId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("ux_accounting_periods_tenant_month");

                    b.ToTable("accounting_periods", "finance");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Ledger.FactPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("FactType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("fact_type");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date")
                        .HasColumnName("occurred_on");

                    b.Property<DateTimeOffset?>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at_utc");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_fact_postings");

                    b.HasIndex("TenantId", "OccurredOn")
                        .HasDatabaseName("ix_fact_postings_tenant_waiting")
                        .HasFilter("status = 'Waiting'");

                    b.HasIndex("TenantId", "FactType", "Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_fact_postings_tenant_fact_reference");

                    b.ToTable("fact_postings", "finance");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Ledger.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset?>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at_utc");

                    b.Property<string>("Reference")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("reference");

                    b.Property<Guid?>("ReversesId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("TenantId", "EntryDate")
                        .HasDatabaseName("ix_journal_entries_tenant_posted_date")
                        .HasFilter("status = 'Posted'");

                    b.HasIndex("TenantId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ux_journal_entries_tenant_number");

                    b.ToTable("journal_entries", "finance");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Ledger.PostingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("FactType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("fact_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_posting_rules");

                    b.HasIndex("TenantId", "FactType")
                        .IsUnique()
                        .HasDatabaseName("ux_posting_rules_tenant_fact");

                    b.ToTable("posting_rules", "finance");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Payables.PayableItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("DocumentDate")
                        .HasColumnType("date")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("document_number");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("supplier_code");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("SupplierInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_invoice_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_payable_items");

                    b.HasIndex("TenantId", "DueDate")
                        .HasDatabaseName("ix_payable_items_tenant_due")
                        .HasFilter("status IN ('Open', 'PartiallySettled')");

                    b.HasIndex("TenantId", "SupplierInvoiceId")
                        .IsUnique()
                        .HasDatabaseName("ux_payable_items_tenant_document");

                    b.HasIndex("TenantId", "SupplierId", "DueDate")
                        .HasDatabaseName("ix_payable_items_tenant_supplier_outstanding")
                        .HasFilter("status IN ('Open', 'PartiallySettled')");

                    b.ToTable("payable_items", "finance");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Payments.SupplierPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("method");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("number");

                    b.Property<DateOnly>("PaidOn")
                        .HasColumnType("date")
                        .HasColumnName("paid_on");

                    b.Property<string>("Reference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("supplier_code");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_supplier_payments");

                    b.HasIndex("TenantId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ux_supplier_payments_tenant_number");

                    b.HasIndex("TenantId", "SupplierId", "PaidOn")
                        .HasDatabaseName("ix_supplier_payments_tenant_unallocated")
                        .HasFilter("status IN ('Unallocated', 'PartiallyAllocated')");

                    b.ToTable("supplier_payments", "finance");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Receipts.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("method");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("number");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date")
                        .HasColumnName("received_on");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_receipts");

                    b.HasIndex("TenantId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ux_receipts_tenant_number");

                    b.HasIndex("TenantId", "CustomerId", "ReceivedOn")
                        .HasDatabaseName("ix_receipts_tenant_unallocated")
                        .HasFilter("status IN ('Unallocated', 'PartiallyAllocated')");

                    b.ToTable("receipts", "finance");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Receivables.OpenItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("DocumentDate")
                        .HasColumnType("date")
                        .HasColumnName("document_date");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("document_number");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_open_items");

                    b.HasIndex("TenantId", "DocumentId")
                        .IsUnique()
                        .HasDatabaseName("ux_open_items_tenant_document");

                    b.HasIndex("TenantId", "CustomerId", "DueDate")
                        .HasDatabaseName("ix_open_items_tenant_outstanding")
                        .HasFilter("status IN ('Open', 'PartiallySettled')");

                    b.ToTable("open_items", "finance");
                });

            modelBuilder.Entity("AutoPartsErp.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("HandlerName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("handler_name");

                    b.Property<DateTimeOffset>("HandledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handled_at_utc");

                    b.HasKey("MessageId", "HandlerName")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("HandledAtUtc")
                        .HasDatabaseName("ix_inbox_messages_handled_at");

                    b.ToTable("inbox_messages", "finance");
                });

            modelBuilder.Entity("AutoPartsErp.Persistence.Numbering.NumberSequence", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("SequenceKey")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("sequence_key");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<int>("NextNumber")
                        .HasColumnType("integer")
                        .HasColumnName("next_number");

                    b.HasKey("TenantId", "SequenceKey", "Year")
                        .HasName("pk_number_sequences");

                    b.ToTable("number_sequences", "finance");
                });

            modelBuilder.Entity("AutoPartsErp.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("NextAttemptAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("outbox_messages", "finance");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Ledger.FactPosting", b =>
                {
                    b.OwnsMany("AutoPartsErp.Modules.Finance.Domain.Ledger.FactAmount", "Amounts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("key");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<Guid>("fact_posting_id")
                                .HasColumnType("uuid")
                                .HasColumnName("fact_posting_id");

                            b1.HasKey("Id")
                                .HasName("pk_fact_posting_amounts");

                            b1.HasIndex("fact_posting_id")
                                .HasDatabaseName("ix_fact_posting_amounts_fact_posting_id");

                            b1.ToTable("fact_posting_amounts", "finance");

                            b1.WithOwner()
                                .HasForeignKey("fact_posting_id")
                                .HasConstraintName("fk_fact_posting_amounts_fact_postings_fact_posting_id");

                            b1.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("FactAmountId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("currency");

                                    b2.HasKey("FactAmountId");

                                    b2.ToTable("fact_posting_amounts", "finance");

                                    b2.WithOwner()
                                        .HasForeignKey("FactAmountId")
                                        .HasConstraintName("fk_fact_posting_amounts_fact_posting_amounts_id");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.Navigation("Amounts");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Ledger.JournalEntry", b =>
                {
                    b.OwnsMany("AutoPartsErp.Modules.Finance.Domain.Ledger.JournalLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AccountCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("account_code");

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("account_id");

                            b1.Property<string>("Narrative")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("narrative");

                            b1.Property<string>("Side")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("side");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<Guid>("journal_entry_id")
                                .HasColumnType("uuid")
                                .HasColumnName("journal_entry_id");

                            b1.HasKey("Id")
                                .HasName("pk_journal_lines");

                            b1.HasIndex("journal_entry_id")
                                .HasDatabaseName("ix_journal_lines_journal_entry_id");

                            b1.HasIndex("TenantId", "AccountId")
                                .HasDatabaseName("ix_journal_lines_tenant_account");

                            b1.ToTable("journal_lines", "finance");

                            b1.WithOwner()
                                .HasForeignKey("journal_entry_id")
                                .HasConstraintName("fk_journal_lines_journal_entries_journal_entry_id");

                            b1.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("JournalLineId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("currency");

                                    b2.HasKey("JournalLineId");

                                    b2.ToTable("journal_lines", "finance");

                                    b2.WithOwner()
                                        .HasForeignKey("JournalLineId")
                                        .HasConstraintName("fk_journal_lines_journal_lines_id");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Ledger.PostingRule", b =>
                {
                    b.OwnsMany("AutoPartsErp.Modules.Finance.Domain.Ledger.PostingRuleLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AccountCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("account_code");

                            b1.Property<string>("AmountKey")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("amount_key");

                            b1.Property<string>("Narrative")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("narrative");

                            b1.Property<string>("Side")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("side");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<Guid>("posting_rule_id")
                                .HasColumnType("uuid")
                                .HasColumnName("posting_rule_id");

                            b1.HasKey("Id")
                                .HasName("pk_posting_rule_lines");

                            b1.HasIndex("posting_rule_id")
                                .HasDatabaseName("ix_posting_rule_lines_posting_rule_id");

                            b1.ToTable("posting_rule_lines", "finance");

                            b1.WithOwner()
                                .HasForeignKey("posting_rule_id")
                                .HasConstraintName("fk_posting_rule_lines_posting_rules_posting_rule_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Payables.PayableItem", b =>
                {
                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "OriginalAmount", b1 =>
                        {
                            b1.Property<Guid>("PayableItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("original_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("PayableItemId");

                            b1.ToTable("payable_items", "finance");

                            b1.WithOwner()
                                .HasForeignKey("PayableItemId")
                                .HasConstraintName("fk_payable_items_payable_items_id");
                        });

                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "SettledAmount", b1 =>
                        {
                            b1.Property<Guid>("PayableItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("settled_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("settled_currency");

                            b1.HasKey("PayableItemId");

                            b1.ToTable("payable_items", "finance");

                            b1.WithOwner()
                                .HasForeignKey("PayableItemId")
                                .HasConstraintName("fk_payable_items_payable_items_id");
                        });

                    b.Navigation("OriginalAmount")
                        .IsRequired();

                    b.Navigation("SettledAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Payments.SupplierPayment", b =>
                {
                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "AllocatedAmount", b1 =>
                        {
                            b1.Property<Guid>("SupplierPaymentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("allocated_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("allocated_currency");

                            b1.HasKey("SupplierPaymentId");

                            b1.ToTable("supplier_payments", "finance");

                            b1.WithOwner()
                                .HasForeignKey("SupplierPaymentId")
                                .HasConstraintName("fk_supplier_payments_supplier_payments_id");
                        });

                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("SupplierPaymentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("SupplierPaymentId");

                            b1.ToTable("supplier_payments", "finance");

                            b1.WithOwner()
                                .HasForeignKey("SupplierPaymentId")
                                .HasConstraintName("fk_supplier_payments_supplier_payments_id");
                        });

                    b.OwnsMany("AutoPartsErp.Modules.Finance.Domain.Payments.SupplierPaymentAllocation", "Allocations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("AllocatedOn")
                                .HasColumnType("date")
                                .HasColumnName("allocated_on");

                            b1.Property<string>("DocumentNumber")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("document_number");

                            b1.Property<Guid>("PayableItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("payable_item_id");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<Guid>("supplier_payment_id")
                                .HasColumnType("uuid")
                                .HasColumnName("supplier_payment_id");

                            b1.HasKey("Id")
                                .HasName("pk_supplier_payment_allocations");

                            b1.HasIndex("PayableItemId")
                                .HasDatabaseName("ix_supplier_payment_allocations_payable_item");

                            b1.HasIndex("supplier_payment_id")
                                .HasDatabaseName("ix_supplier_payment_allocations_supplier_payment_id");

                            b1.ToTable("supplier_payment_allocations", "finance");

                            b1.WithOwner()
                                .HasForeignKey("supplier_payment_id")
                                .HasConstraintName("fk_supplier_payment_allocations_supplier_payments_supplier_pay");

                            b1.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("SupplierPaymentAllocationId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("currency");

                                    b2.HasKey("SupplierPaymentAllocationId");

                                    b2.ToTable("supplier_payment_allocations", "finance");

                                    b2.WithOwner()
                                        .HasForeignKey("SupplierPaymentAllocationId")
                                        .HasConstraintName("fk_supplier_payment_allocations_supplier_payment_allocations_id");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.Navigation("AllocatedAmount")
                        .IsRequired();

                    b.Navigation("Allocations");

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Receipts.Receipt", b =>
                {
                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "AllocatedAmount", b1 =>
                        {
                            b1.Property<Guid>("ReceiptId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("allocated_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("allocated_currency");

                            b1.HasKey("ReceiptId");

                            b1.ToTable("receipts", "finance");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptId")
                                .HasConstraintName("fk_receipts_receipts_id");
                        });

                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("ReceiptId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("ReceiptId");

                            b1.ToTable("receipts", "finance");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptId")
                                .HasConstraintName("fk_receipts_receipts_id");
                        });

                    b.OwnsMany("AutoPartsErp.Modules.Finance.Domain.Receipts.ReceiptAllocation", "Allocations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("AllocatedOn")
                                .HasColumnType("date")
                                .HasColumnName("allocated_on");

                            b1.Property<string>("DocumentNumber")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("document_number");

                            b1.Property<Guid>("OpenItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("open_item_id");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<Guid>("receipt_id")
                                .HasColumnType("uuid")
                                .HasColumnName("receipt_id");

                            b1.HasKey("Id")
                                .HasName("pk_receipt_allocations");

                            b1.HasIndex("OpenItemId")
                                .HasDatabaseName("ix_receipt_allocations_open_item");

                            b1.HasIndex("receipt_id")
                                .HasDatabaseName("ix_receipt_allocations_receipt_id");

                            b1.ToTable("receipt_allocations", "finance");

                            b1.WithOwner()
                                .HasForeignKey("receipt_id")
                                .HasConstraintName("fk_receipt_allocations_receipts_receipt_id");

                            b1.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("ReceiptAllocationId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("currency");

                                    b2.HasKey("ReceiptAllocationId");

                                    b2.ToTable("receipt_allocations", "finance");

                                    b2.WithOwner()
                                        .HasForeignKey("ReceiptAllocationId")
                                        .HasConstraintName("fk_receipt_allocations_receipt_allocations_id");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.Navigation("AllocatedAmount")
                        .IsRequired();

                    b.Navigation("Allocations");

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Finance.Domain.Receivables.OpenItem", b =>
                {
                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "OriginalAmount", b1 =>
                        {
                            b1.Property<Guid>("OpenItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("original_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("OpenItemId");

                            b1.ToTable("open_items", "finance");

                            b1.WithOwner()
                                .HasForeignKey("OpenItemId")
                                .HasConstraintName("fk_open_items_open_items_id");
                        });

                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "SettledAmount", b1 =>
                        {
                            b1.Property<Guid>("OpenItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("settled_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("settled_currency");

                            b1.HasKey("OpenItemId");

                            b1.ToTable("open_items", "finance");

                            b1.WithOwner()
                                .HasForeignKey("OpenItemId")
                                .HasConstraintName("fk_open_items_open_items_id");
                        });

                    b.Navigation("OriginalAmount")
                        .IsRequired();

                    b.Navigation("SettledAmount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
