// <auto-generated />
using System;
using AutoPartsErp.Modules.Invoicing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoPartsErp.Modules.Invoicing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InvoicingDbContext))]
    [Migration("20260908084917_InvoiceLineSalesOrderLine")]
    partial class InvoiceLineSalesOrderLine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("invoicing")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoPartsErp.Modules.Invoicing.Domain.Invoices.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreditReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("credit_reason");

                    b.Property<string>("CreditedDocumentNumber")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("credited_document_number");

                    b.Property<Guid?>("CreditedInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("credited_invoice_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("CustomerCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("customer_country");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerTaxNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_tax_number");

                    b.Property<DateOnly>("DocumentDate")
                        .HasColumnType("date")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("document_number");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<string>("QrCode")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("qr_code");

                    b.Property<Guid?>("SalesOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_order_id");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<int>("SeriesNumber")
                        .HasColumnType("integer")
                        .HasColumnName("series_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SystemEntryDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("system_entry_date_utc");

                    b.Property<string>("TaxRegion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_region");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("void_reason");

                    b.Property<DateTimeOffset?>("VoidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("TenantId", "CreditedInvoiceId")
                        .HasDatabaseName("ix_invoices_tenant_credited")
                        .HasFilter("credited_invoice_id IS NOT NULL");

                    b.HasIndex("TenantId", "DocumentDate")
                        .HasDatabaseName("ix_invoices_tenant_date");

                    b.HasIndex("TenantId", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_invoices_tenant_number")
                        .HasFilter("document_number <> ''");

                    b.HasIndex("TenantId", "CustomerId", "DocumentDate")
                        .HasDatabaseName("ix_invoices_tenant_customer_date");

                    b.HasIndex("TenantId", "SeriesId", "SeriesNumber")
                        .HasDatabaseName("ix_invoices_tenant_series_number");

                    b.ToTable("invoices", "invoicing");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Invoicing.Domain.Series.DocumentSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<int>("NextNumber")
                        .HasColumnType("integer")
                        .HasColumnName("next_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("ValidatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at_utc");

                    b.Property<string>("ValidationCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("validation_code");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_document_series");

                    b.HasIndex("TenantId", "Type", "Code", "Year")
                        .IsUnique()
                        .HasDatabaseName("ux_document_series_tenant_type_code_year");

                    b.HasIndex("TenantId", "Type", "Year", "Status")
                        .HasDatabaseName("ix_document_series_tenant_type_year_status");

                    b.ToTable("document_series", "invoicing");
                });

            modelBuilder.Entity("AutoPartsErp.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("HandlerName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("handler_name");

                    b.Property<DateTimeOffset>("HandledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handled_at_utc");

                    b.HasKey("MessageId", "HandlerName")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("HandledAtUtc")
                        .HasDatabaseName("ix_inbox_messages_handled_at");

                    b.ToTable("inbox_messages", "invoicing");
                });

            modelBuilder.Entity("AutoPartsErp.Persistence.Numbering.NumberSequence", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("SequenceKey")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("sequence_key");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<int>("NextNumber")
                        .HasColumnType("integer")
                        .HasColumnName("next_number");

                    b.HasKey("TenantId", "SequenceKey", "Year")
                        .HasName("pk_number_sequences");

                    b.ToTable("number_sequences", "invoicing");
                });

            modelBuilder.Entity("AutoPartsErp.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("NextAttemptAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("outbox_messages", "invoicing");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Invoicing.Domain.Invoices.Invoice", b =>
                {
                    b.OwnsOne("AutoPartsErp.Modules.Invoicing.Domain.Invoices.Atcud", "Atcud", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Number")
                                .HasColumnType("integer")
                                .HasColumnName("atcud_number");

                            b1.Property<string>("ValidationCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("atcud_validation_code");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("invoices", "invoicing");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId")
                                .HasConstraintName("fk_invoices_invoices_id");
                        });

                    b.OwnsOne("AutoPartsErp.Modules.Invoicing.Domain.Invoices.DocumentSignature", "Signature", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Printed")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("signature_printed");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("signature");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("invoices", "invoicing");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId")
                                .HasConstraintName("fk_invoices_invoices_id");
                        });

                    b.OwnsMany("AutoPartsErp.Modules.Invoicing.Domain.Invoices.InvoiceLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("CreditsLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("credits_line_id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("description");

                            b1.Property<decimal>("DiscountPercent")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)")
                                .HasColumnName("discount_percent");

                            b1.Property<int>("Number")
                                .HasColumnType("integer")
                                .HasColumnName("line_number");

                            b1.Property<Guid>("PartId")
                                .HasColumnType("uuid")
                                .HasColumnName("part_id");

                            b1.Property<Guid?>("SalesOrderLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("sales_order_line_id");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("sku");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<Guid>("invoice_id")
                                .HasColumnType("uuid")
                                .HasColumnName("invoice_id");

                            b1.HasKey("Id")
                                .HasName("pk_invoice_lines");

                            b1.HasIndex("invoice_id")
                                .HasDatabaseName("ix_invoice_lines_invoice_id");

                            b1.ToTable("invoice_lines", "invoicing");

                            b1.WithOwner()
                                .HasForeignKey("invoice_id")
                                .HasConstraintName("fk_invoice_lines_invoices_invoice_id");

                            b1.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Quantity", "CreditedQuantity", b2 =>
                                {
                                    b2.Property<Guid>("InvoiceLineId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("credited_quantity_unit");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("credited_quantity");

                                    b2.HasKey("InvoiceLineId");

                                    b2.ToTable("invoice_lines", "invoicing");

                                    b2.WithOwner()
                                        .HasForeignKey("InvoiceLineId")
                                        .HasConstraintName("fk_invoice_lines_invoice_lines_id");
                                });

                            b1.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Quantity", "Quantity", b2 =>
                                {
                                    b2.Property<Guid>("InvoiceLineId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("unit_code");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("quantity");

                                    b2.HasKey("InvoiceLineId");

                                    b2.ToTable("invoice_lines", "invoicing");

                                    b2.WithOwner()
                                        .HasForeignKey("InvoiceLineId")
                                        .HasConstraintName("fk_invoice_lines_invoice_lines_id");
                                });

                            b1.OwnsOne("AutoPartsErp.Modules.Invoicing.Domain.Invoices.VatRate", "VatRate", b2 =>
                                {
                                    b2.Property<Guid>("InvoiceLineId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Category")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("vat_category");

                                    b2.Property<string>("ExemptionCode")
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("vat_exemption_code");

                                    b2.Property<string>("ExemptionReason")
                                        .HasMaxLength(60)
                                        .HasColumnType("character varying(60)")
                                        .HasColumnName("vat_exemption_reason");

                                    b2.Property<decimal>("Percent")
                                        .HasPrecision(9, 4)
                                        .HasColumnType("numeric(9,4)")
                                        .HasColumnName("vat_percent");

                                    b2.HasKey("InvoiceLineId");

                                    b2.ToTable("invoice_lines", "invoicing");

                                    b2.WithOwner()
                                        .HasForeignKey("InvoiceLineId")
                                        .HasConstraintName("fk_invoice_lines_invoice_lines_id");
                                });

                            b1.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "UnitPrice", b2 =>
                                {
                                    b2.Property<Guid>("InvoiceLineId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("unit_price");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("unit_price_currency");

                                    b2.HasKey("InvoiceLineId");

                                    b2.ToTable("invoice_lines", "invoicing");

                                    b2.WithOwner()
                                        .HasForeignKey("InvoiceLineId")
                                        .HasConstraintName("fk_invoice_lines_invoice_lines_id");
                                });

                            b1.Navigation("CreditedQuantity")
                                .IsRequired();

                            b1.Navigation("Quantity")
                                .IsRequired();

                            b1.Navigation("UnitPrice")
                                .IsRequired();

                            b1.Navigation("VatRate")
                                .IsRequired();
                        });

                    b.Navigation("Atcud");

                    b.Navigation("Lines");

                    b.Navigation("Signature");
                });
#pragma warning restore 612, 618
        }
    }
}
