// <auto-generated />
using System;
using AutoPartsErp.Modules.Inventory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoPartsErp.Modules.Inventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoPartsErp.Modules.Inventory.Domain.Stock.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DefaultBinId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_bin_id");

                    b.Property<DateTimeOffset?>("LastCountedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_counted_at_utc");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("Part")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("unit");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_items");

                    b.HasIndex("TenantId", "WarehouseId")
                        .HasDatabaseName("ix_stock_items_tenant_warehouse");

                    b.HasIndex("TenantId", "Part", "WarehouseId")
                        .IsUnique()
                        .HasDatabaseName("ux_stock_items_tenant_part_warehouse");

                    b.ToTable("stock_items", "inventory");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Inventory.Domain.Stock.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BinId")
                        .HasColumnType("uuid")
                        .HasColumnName("bin_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("Part")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_movements");

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .HasDatabaseName("ix_stock_movements_tenant_date");

                    b.HasIndex("TenantId", "Part", "WarehouseId", "OccurredAtUtc")
                        .HasDatabaseName("ix_stock_movements_part_warehouse_date");

                    b.ToTable("stock_movements", "inventory");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Inventory.Domain.Warehouses.StorageBin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<int>("PickSequence")
                        .HasColumnType("integer")
                        .HasColumnName("pick_sequence");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_storage_bins");

                    b.HasIndex("WarehouseId", "PickSequence")
                        .HasDatabaseName("ix_storage_bins_pick_route");

                    b.HasIndex("TenantId", "WarehouseId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_storage_bins_warehouse_code");

                    b.ToTable("storage_bins", "inventory");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Inventory.Domain.Warehouses.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsNegativeStock")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_negative_stock");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresBinTracking")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_bin_tracking");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_warehouses_tenant_code");

                    b.ToTable("warehouses", "inventory");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Inventory.Domain.Stock.StockItem", b =>
                {
                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Quantity", "OnHand", b1 =>
                        {
                            b1.Property<Guid>("StockItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("on_hand_unit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("on_hand");

                            b1.HasKey("StockItemId");

                            b1.ToTable("stock_items", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("StockItemId")
                                .HasConstraintName("fk_stock_items_stock_items_id");
                        });

                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Quantity", "OnOrder", b1 =>
                        {
                            b1.Property<Guid>("StockItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("on_order_unit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("on_order");

                            b1.HasKey("StockItemId");

                            b1.ToTable("stock_items", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("StockItemId")
                                .HasConstraintName("fk_stock_items_stock_items_id");
                        });

                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Quantity", "ReorderPoint", b1 =>
                        {
                            b1.Property<Guid>("StockItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("reorder_point_unit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("reorder_point");

                            b1.HasKey("StockItemId");

                            b1.ToTable("stock_items", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("StockItemId")
                                .HasConstraintName("fk_stock_items_stock_items_id");
                        });

                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Quantity", "ReorderQuantity", b1 =>
                        {
                            b1.Property<Guid>("StockItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("reorder_quantity_unit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("reorder_quantity");

                            b1.HasKey("StockItemId");

                            b1.ToTable("stock_items", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("StockItemId")
                                .HasConstraintName("fk_stock_items_stock_items_id");
                        });

                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Quantity", "Reserved", b1 =>
                        {
                            b1.Property<Guid>("StockItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("reserved_unit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("reserved");

                            b1.HasKey("StockItemId");

                            b1.ToTable("stock_items", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("StockItemId")
                                .HasConstraintName("fk_stock_items_stock_items_id");
                        });

                    b.OwnsMany("AutoPartsErp.Modules.Inventory.Domain.Stock.StockReservation", "Reservations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<DateTimeOffset?>("ExpiresAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("expires_at_utc");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("status");

                            b1.Property<Guid>("stock_item_id")
                                .HasColumnType("uuid")
                                .HasColumnName("stock_item_id");

                            b1.HasKey("Id")
                                .HasName("pk_stock_reservations");

                            b1.HasIndex("stock_item_id")
                                .HasDatabaseName("ix_stock_reservations_stock_item_id");

                            b1.HasIndex("Status", "ExpiresAtUtc")
                                .HasDatabaseName("ix_stock_reservations_status_expiry");

                            b1.ToTable("stock_reservations", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("stock_item_id")
                                .HasConstraintName("fk_stock_reservations_stock_items_stock_item_id");

                            b1.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Quantity", "Quantity", b2 =>
                                {
                                    b2.Property<Guid>("StockReservationId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("unit");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("quantity");

                                    b2.HasKey("StockReservationId");

                                    b2.ToTable("stock_reservations", "inventory");

                                    b2.WithOwner()
                                        .HasForeignKey("StockReservationId")
                                        .HasConstraintName("fk_stock_reservations_stock_reservations_id");
                                });

                            b1.OwnsOne("AutoPartsErp.Modules.Inventory.Domain.Stock.MovementReference", "Reference", b2 =>
                                {
                                    b2.Property<Guid>("StockReservationId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Note")
                                        .HasMaxLength(400)
                                        .HasColumnType("character varying(400)")
                                        .HasColumnName("reference_note");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasMaxLength(40)
                                        .HasColumnType("character varying(40)")
                                        .HasColumnName("reference_number");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("character varying(30)")
                                        .HasColumnName("reference_type");

                                    b2.HasKey("StockReservationId");

                                    b2.ToTable("stock_reservations", "inventory");

                                    b2.WithOwner()
                                        .HasForeignKey("StockReservationId")
                                        .HasConstraintName("fk_stock_reservations_stock_reservations_id");
                                });

                            b1.Navigation("Quantity")
                                .IsRequired();

                            b1.Navigation("Reference")
                                .IsRequired();
                        });

                    b.Navigation("OnHand")
                        .IsRequired();

                    b.Navigation("OnOrder")
                        .IsRequired();

                    b.Navigation("ReorderPoint");

                    b.Navigation("ReorderQuantity");

                    b.Navigation("Reservations");

                    b.Navigation("Reserved")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Inventory.Domain.Stock.StockMovement", b =>
                {
                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Quantity", "BalanceAfter", b1 =>
                        {
                            b1.Property<Guid>("StockMovementId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("balance_after_unit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("balance_after");

                            b1.HasKey("StockMovementId");

                            b1.ToTable("stock_movements", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("StockMovementId")
                                .HasConstraintName("fk_stock_movements_stock_movements_id");
                        });

                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("StockMovementId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("unit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("quantity");

                            b1.HasKey("StockMovementId");

                            b1.ToTable("stock_movements", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("StockMovementId")
                                .HasConstraintName("fk_stock_movements_stock_movements_id");
                        });

                    b.OwnsOne("AutoPartsErp.Modules.Inventory.Domain.Stock.MovementReference", "Reference", b1 =>
                        {
                            b1.Property<Guid>("StockMovementId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Note")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("reference_note");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("reference_number");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("reference_type");

                            b1.HasKey("StockMovementId");

                            b1.HasIndex("Number")
                                .HasDatabaseName("ix_stock_movements_reference_number");

                            b1.ToTable("stock_movements", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("StockMovementId")
                                .HasConstraintName("fk_stock_movements_stock_movements_id");
                        });

                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "UnitCost", b1 =>
                        {
                            b1.Property<Guid>("StockMovementId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("unit_cost");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("unit_cost_currency");

                            b1.HasKey("StockMovementId");

                            b1.ToTable("stock_movements", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("StockMovementId")
                                .HasConstraintName("fk_stock_movements_stock_movements_id");
                        });

                    b.Navigation("BalanceAfter")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();

                    b.Navigation("Reference")
                        .IsRequired();

                    b.Navigation("UnitCost");
                });
#pragma warning restore 612, 618
        }
    }
}
