// <auto-generated />
using System;
using AutoPartsErp.Modules.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoPartsErp.Modules.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260825161117_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoPartsErp.Modules.Catalog.Domain.Brands.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsOriginalEquipment")
                        .HasColumnType("boolean")
                        .HasColumnName("is_original_equipment");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_brands");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_brands_tenant_code");

                    b.ToTable("brands", "catalog");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Catalog.Domain.Categories.PartCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_tenant_code");

                    b.ToTable("categories", "catalog");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Catalog.Domain.Parts.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresCoreReturn")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_core_return");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StockUnit")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("stock_unit");

                    b.Property<Guid?>("SupersededByPartId")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_part_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_parts");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_parts_status");

                    b.HasIndex("TenantId", "BrandId")
                        .HasDatabaseName("ix_parts_tenant_brand");

                    b.HasIndex("TenantId", "CategoryId")
                        .HasDatabaseName("ix_parts_tenant_category");

                    b.HasIndex("TenantId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("ux_parts_tenant_sku");

                    b.ToTable("parts", "catalog");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Catalog.Domain.Parts.Part", b =>
                {
                    b.OwnsOne("AutoPartsErp.Modules.Catalog.Domain.Parts.PackageSpec", "Package", b1 =>
                        {
                            b1.Property<Guid>("PartId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal?>("HeightMm")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("height_mm");

                            b1.Property<bool>("IsDangerousGoods")
                                .HasColumnType("boolean")
                                .HasColumnName("is_dangerous_goods");

                            b1.Property<decimal?>("LengthMm")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("length_mm");

                            b1.Property<string>("UnNumber")
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("un_number");

                            b1.Property<decimal>("WeightKg")
                                .HasPrecision(12, 4)
                                .HasColumnType("numeric(12,4)")
                                .HasColumnName("weight_kg");

                            b1.Property<decimal?>("WidthMm")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("width_mm");

                            b1.HasKey("PartId");

                            b1.ToTable("parts", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("PartId")
                                .HasConstraintName("fk_parts_parts_id");
                        });

                    b.OwnsOne("AutoPartsErp.Modules.Catalog.Domain.Parts.PartNumber", "ManufacturerPartNumber", b1 =>
                        {
                            b1.Property<Guid>("PartId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Display")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("manufacturer_part_number");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("manufacturer_part_number_normalized");

                            b1.HasKey("PartId");

                            b1.HasIndex("Normalized")
                                .HasDatabaseName("ix_parts_mpn_normalized");

                            b1.ToTable("parts", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("PartId")
                                .HasConstraintName("fk_parts_parts_id");
                        });

                    b.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "CoreCharge", b1 =>
                        {
                            b1.Property<Guid>("PartId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("core_charge_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("core_charge_currency");

                            b1.HasKey("PartId");

                            b1.ToTable("parts", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("PartId")
                                .HasConstraintName("fk_parts_parts_id");
                        });

                    b.OwnsMany("AutoPartsErp.Modules.Catalog.Domain.Parts.CrossReference", "CrossReferences", b1 =>
                        {
                            b1.Property<long>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("id"));

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("kind");

                            b1.Property<string>("NormalizedNumber")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("normalized_number");

                            b1.Property<string>("Notes")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("notes");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("number");

                            b1.Property<string>("SourceBrand")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("source_brand");

                            b1.Property<Guid>("part_id")
                                .HasColumnType("uuid")
                                .HasColumnName("part_id");

                            b1.HasKey("id")
                                .HasName("pk_part_cross_references");

                            b1.HasIndex("NormalizedNumber")
                                .HasDatabaseName("ix_part_cross_references_normalized_number");

                            b1.HasIndex("part_id", "Kind")
                                .HasDatabaseName("ix_part_cross_references_part_kind");

                            b1.ToTable("part_cross_references", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("part_id")
                                .HasConstraintName("fk_part_cross_references_parts_part_id");
                        });

                    b.OwnsMany("AutoPartsErp.Modules.Catalog.Domain.Parts.Fitment", "Fitments", b1 =>
                        {
                            b1.Property<long>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("id"));

                            b1.Property<string>("EngineCode")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("engine_code");

                            b1.Property<string>("Make")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("make");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("model");

                            b1.Property<string>("Notes")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("notes");

                            b1.Property<string>("Position")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("position");

                            b1.Property<int>("YearFrom")
                                .HasColumnType("integer")
                                .HasColumnName("year_from");

                            b1.Property<int>("YearTo")
                                .HasColumnType("integer")
                                .HasColumnName("year_to");

                            b1.Property<Guid>("part_id")
                                .HasColumnType("uuid")
                                .HasColumnName("part_id");

                            b1.HasKey("id")
                                .HasName("pk_part_fitments");

                            b1.HasIndex("part_id")
                                .HasDatabaseName("ix_part_fitments_part_id");

                            b1.HasIndex("Make", "Model", "YearFrom", "YearTo")
                                .HasDatabaseName("ix_part_fitments_vehicle");

                            b1.ToTable("part_fitments", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("part_id")
                                .HasConstraintName("fk_part_fitments_parts_part_id");
                        });

                    b.Navigation("CoreCharge");

                    b.Navigation("CrossReferences");

                    b.Navigation("Fitments");

                    b.Navigation("ManufacturerPartNumber")
                        .IsRequired();

                    b.Navigation("Package")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
