// <auto-generated />
using System;
using AutoPartsErp.Modules.Partners.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoPartsErp.Modules.Partners.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PartnersDbContext))]
    [Migration("20260831141836_InitialPartners")]
    partial class InitialPartners
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("partners")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoPartsErp.Modules.Partners.Domain.Partners.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("HoldReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hold_reason");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<int>("Roles")
                        .HasColumnType("integer")
                        .HasColumnName("roles");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TradingName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trading_name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_partners");

                    b.HasIndex("Roles")
                        .HasDatabaseName("ix_partners_roles");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_partners_status");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_partners_tenant_code");

                    b.ToTable("partners", "partners");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Partners.Domain.Partners.Partner", b =>
                {
                    b.OwnsOne("AutoPartsErp.Modules.Partners.Domain.Partners.TaxNumber", "TaxNumber", b1 =>
                        {
                            b1.Property<Guid>("PartnerId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("tax_country_code");

                            b1.Property<bool>("IsVerified")
                                .HasColumnType("boolean")
                                .HasColumnName("tax_number_verified");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("tax_number");

                            b1.HasKey("PartnerId");

                            b1.HasIndex("CountryCode", "Value")
                                .HasDatabaseName("ix_partners_tax_number");

                            b1.ToTable("partners", "partners");

                            b1.WithOwner()
                                .HasForeignKey("PartnerId")
                                .HasConstraintName("fk_partners_partners_id");
                        });

                    b.OwnsMany("AutoPartsErp.Modules.Partners.Domain.Partners.Address", "Addresses", b1 =>
                        {
                            b1.Property<long>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("id"));

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("country_code");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("kind");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("line2");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("notes");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("postcode");

                            b1.Property<Guid>("partner_id")
                                .HasColumnType("uuid")
                                .HasColumnName("partner_id");

                            b1.HasKey("id")
                                .HasName("pk_partner_addresses");

                            b1.HasIndex("partner_id", "Kind")
                                .HasDatabaseName("ix_partner_addresses_partner_kind");

                            b1.ToTable("partner_addresses", "partners");

                            b1.WithOwner()
                                .HasForeignKey("partner_id")
                                .HasConstraintName("fk_partner_addresses_partners_partner_id");
                        });

                    b.OwnsMany("AutoPartsErp.Modules.Partners.Domain.Partners.ContactDetail", "Contacts", b1 =>
                        {
                            b1.Property<long>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("id"));

                            b1.Property<string>("Email")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean")
                                .HasColumnName("is_primary");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("name");

                            b1.Property<string>("Phone")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("phone");

                            b1.Property<string>("Role")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("role");

                            b1.Property<Guid>("partner_id")
                                .HasColumnType("uuid")
                                .HasColumnName("partner_id");

                            b1.HasKey("id")
                                .HasName("pk_partner_contacts");

                            b1.HasIndex("partner_id")
                                .HasDatabaseName("ix_partner_contacts_partner_id");

                            b1.ToTable("partner_contacts", "partners");

                            b1.WithOwner()
                                .HasForeignKey("partner_id")
                                .HasConstraintName("fk_partner_contacts_partners_partner_id");
                        });

                    b.OwnsOne("AutoPartsErp.Modules.Partners.Domain.Partners.CustomerTerms", "CustomerTerms", b1 =>
                        {
                            b1.Property<Guid>("partner_id")
                                .HasColumnType("uuid")
                                .HasColumnName("partner_id");

                            b1.Property<string>("PriceListCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("price_list_code");

                            b1.HasKey("partner_id")
                                .HasName("pk_partner_customer_terms");

                            b1.ToTable("partner_customer_terms", "partners");

                            b1.WithOwner()
                                .HasForeignKey("partner_id")
                                .HasConstraintName("fk_partner_customer_terms_partners_partner_id");

                            b1.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "CreditLimit", b2 =>
                                {
                                    b2.Property<Guid>("CustomerTermspartner_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("partner_id");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("credit_limit");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("credit_currency");

                                    b2.HasKey("CustomerTermspartner_id");

                                    b2.ToTable("partner_customer_terms", "partners");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerTermspartner_id")
                                        .HasConstraintName("fk_partner_customer_terms_partner_customer_terms_partner_id");
                                });

                            b1.OwnsOne("AutoPartsErp.Modules.Partners.Domain.Partners.PaymentTerms", "PaymentTerms", b2 =>
                                {
                                    b2.Property<Guid>("CustomerTermspartner_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("partner_id");

                                    b2.Property<int>("DueInDays")
                                        .HasColumnType("integer")
                                        .HasColumnName("payment_due_in_days");

                                    b2.Property<bool>("EndOfMonth")
                                        .HasColumnType("boolean")
                                        .HasColumnName("payment_end_of_month");

                                    b2.Property<string>("Method")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("payment_method");

                                    b2.HasKey("CustomerTermspartner_id");

                                    b2.ToTable("partner_customer_terms", "partners");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerTermspartner_id")
                                        .HasConstraintName("fk_partner_customer_terms_partner_customer_terms_partner_id");
                                });

                            b1.Navigation("CreditLimit")
                                .IsRequired();

                            b1.Navigation("PaymentTerms")
                                .IsRequired();
                        });

                    b.OwnsOne("AutoPartsErp.Modules.Partners.Domain.Partners.SupplierTerms", "SupplierTerms", b1 =>
                        {
                            b1.Property<Guid>("partner_id")
                                .HasColumnType("uuid")
                                .HasColumnName("partner_id");

                            b1.Property<int>("LeadTimeDays")
                                .HasColumnType("integer")
                                .HasColumnName("lead_time_days");

                            b1.Property<string>("OurAccountNumber")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("our_account_number");

                            b1.HasKey("partner_id")
                                .HasName("pk_partner_supplier_terms");

                            b1.ToTable("partner_supplier_terms", "partners");

                            b1.WithOwner()
                                .HasForeignKey("partner_id")
                                .HasConstraintName("fk_partner_supplier_terms_partners_partner_id");

                            b1.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "MinimumOrderValue", b2 =>
                                {
                                    b2.Property<Guid>("SupplierTermspartner_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("partner_id");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("minimum_order_value");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("minimum_order_currency");

                                    b2.HasKey("SupplierTermspartner_id");

                                    b2.ToTable("partner_supplier_terms", "partners");

                                    b2.WithOwner()
                                        .HasForeignKey("SupplierTermspartner_id")
                                        .HasConstraintName("fk_partner_supplier_terms_partner_supplier_terms_partner_id");
                                });

                            b1.OwnsOne("AutoPartsErp.Modules.Partners.Domain.Partners.PaymentTerms", "PaymentTerms", b2 =>
                                {
                                    b2.Property<Guid>("SupplierTermspartner_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("partner_id");

                                    b2.Property<int>("DueInDays")
                                        .HasColumnType("integer")
                                        .HasColumnName("payment_due_in_days");

                                    b2.Property<bool>("EndOfMonth")
                                        .HasColumnType("boolean")
                                        .HasColumnName("payment_end_of_month");

                                    b2.Property<string>("Method")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("payment_method");

                                    b2.HasKey("SupplierTermspartner_id");

                                    b2.ToTable("partner_supplier_terms", "partners");

                                    b2.WithOwner()
                                        .HasForeignKey("SupplierTermspartner_id")
                                        .HasConstraintName("fk_partner_supplier_terms_partner_supplier_terms_partner_id");
                                });

                            b1.Navigation("MinimumOrderValue");

                            b1.Navigation("PaymentTerms")
                                .IsRequired();
                        });

                    b.Navigation("Addresses");

                    b.Navigation("Contacts");

                    b.Navigation("CustomerTerms");

                    b.Navigation("SupplierTerms");

                    b.Navigation("TaxNumber")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
