// <auto-generated />
using System;
using AutoPartsErp.Modules.Purchasing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoPartsErp.Modules.Purchasing.Infrastructure.Migrations
{
    [DbContext(typeof(PurchasingDbContext))]
    [Migration("20260902091604_AddOutbox")]
    partial class AddOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("purchasing")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoPartsErp.Modules.Purchasing.Domain.Orders.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClosureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("closure_reason");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("DeliverToWarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("deliver_to_warehouse_id");

                    b.Property<DateOnly?>("ExpectedOn")
                        .HasColumnType("date")
                        .HasColumnName("expected_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("order_number");

                    b.Property<DateOnly?>("OrderedOn")
                        .HasColumnType("date")
                        .HasColumnName("ordered_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("supplier_code");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplierReference")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("supplier_reference");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_purchase_orders");

                    b.HasIndex("TenantId", "ExpectedOn")
                        .HasDatabaseName("ix_purchase_orders_tenant_expected");

                    b.HasIndex("TenantId", "OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_purchase_orders_tenant_number");

                    b.HasIndex("TenantId", "SupplierId", "Status")
                        .HasDatabaseName("ix_purchase_orders_tenant_supplier_status");

                    b.ToTable("purchase_orders", "purchasing");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Purchasing.Domain.Replenishment.ReplenishmentSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<string>("DismissedReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("dismissed_reason");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<decimal>("QuantityAvailable")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity_available");

                    b.Property<DateTimeOffset>("RaisedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at_utc");

                    b.Property<decimal>("ReorderPoint")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("reorder_point");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("SuggestedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("suggested_quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_replenishment_suggestions");

                    b.HasIndex("TenantId", "PartId", "WarehouseId")
                        .IsUnique()
                        .HasDatabaseName("ux_replenishment_suggestions_open")
                        .HasFilter("status = 'Open'");

                    b.HasIndex("TenantId", "Status", "WarehouseId")
                        .HasDatabaseName("ix_replenishment_suggestions_status_warehouse");

                    b.ToTable("replenishment_suggestions", "purchasing");
                });

            modelBuilder.Entity("AutoPartsErp.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("HandlerName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("handler_name");

                    b.Property<DateTimeOffset>("HandledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handled_at_utc");

                    b.HasKey("MessageId", "HandlerName")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("HandledAtUtc")
                        .HasDatabaseName("ix_inbox_messages_handled_at");

                    b.ToTable("inbox_messages", "purchasing");
                });

            modelBuilder.Entity("AutoPartsErp.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("NextAttemptAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("outbox_messages", "purchasing");
                });

            modelBuilder.Entity("AutoPartsErp.Modules.Purchasing.Domain.Orders.PurchaseOrder", b =>
                {
                    b.OwnsMany("AutoPartsErp.Modules.Purchasing.Domain.Orders.PurchaseOrderLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("created_by");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("description");

                            b1.Property<DateTimeOffset?>("ModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("modified_at_utc");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("modified_by");

                            b1.Property<Guid>("PartId")
                                .HasColumnType("uuid")
                                .HasColumnName("part_id");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("sku");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<Guid>("purchase_order_id")
                                .HasColumnType("uuid")
                                .HasColumnName("purchase_order_id");

                            b1.HasKey("Id")
                                .HasName("pk_purchase_order_lines");

                            b1.HasIndex("purchase_order_id")
                                .HasDatabaseName("ix_purchase_order_lines_purchase_order_id");

                            b1.HasIndex("TenantId", "PartId")
                                .HasDatabaseName("ix_purchase_order_lines_tenant_part");

                            b1.ToTable("purchase_order_lines", "purchasing");

                            b1.WithOwner()
                                .HasForeignKey("purchase_order_id")
                                .HasConstraintName("fk_purchase_order_lines_purchase_orders_purchase_order_id");

                            b1.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Quantity", "Quantity", b2 =>
                                {
                                    b2.Property<Guid>("PurchaseOrderLineId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("quantity_unit");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("quantity");

                                    b2.HasKey("PurchaseOrderLineId");

                                    b2.ToTable("purchase_order_lines", "purchasing");

                                    b2.WithOwner()
                                        .HasForeignKey("PurchaseOrderLineId")
                                        .HasConstraintName("fk_purchase_order_lines_purchase_order_lines_id");
                                });

                            b1.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Quantity", "ReceivedQuantity", b2 =>
                                {
                                    b2.Property<Guid>("PurchaseOrderLineId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("received_quantity_unit");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("received_quantity");

                                    b2.HasKey("PurchaseOrderLineId");

                                    b2.ToTable("purchase_order_lines", "purchasing");

                                    b2.WithOwner()
                                        .HasForeignKey("PurchaseOrderLineId")
                                        .HasConstraintName("fk_purchase_order_lines_purchase_order_lines_id");
                                });

                            b1.OwnsOne("AutoPartsErp.SharedKernel.ValueObjects.Money", "UnitPrice", b2 =>
                                {
                                    b2.Property<Guid>("PurchaseOrderLineId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("unit_price");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("unit_price_currency");

                                    b2.HasKey("PurchaseOrderLineId");

                                    b2.ToTable("purchase_order_lines", "purchasing");

                                    b2.WithOwner()
                                        .HasForeignKey("PurchaseOrderLineId")
                                        .HasConstraintName("fk_purchase_order_lines_purchase_order_lines_id");
                                });

                            b1.Navigation("Quantity")
                                .IsRequired();

                            b1.Navigation("ReceivedQuantity")
                                .IsRequired();

                            b1.Navigation("UnitPrice")
                                .IsRequired();
                        });

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
